[package]
name = "arcon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "arcon"
crate-type = ["lib"]

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.82"
rand = "0.8"
